#!/bin/sh
set -e

# Apache gets grumpy about PID files pre-existing
#rm -f /usr/local/apache2/logs/httpd.pid
if [ -e /run/httpd/httpd.pid ]; then
  rm -f /run/httpd/httpd.pid
fi

exec httpd -DFOREGROUND
